export const imageList = [
  { name: "image01.jpg", group: "風景" },
  { name: "image02.png", group: "人物" },
  { name: "image03.gif", group: "動物" },
  { name: "image04.webp", group: "風景" },
  { name: "image05.svg", group: "抽象" },
  { name: "image06.jpg", group: "人物" },
  { name: "image07.png", group: "動物" },
  { name: "image08.gif", group: "風景" },
  { name: "image09.webp", group: "抽象" },
  { name: "image10.svg", group: "人物" },
  { name: "image11.jpg", group: "動物" },
  { name: "image12.png", group: "風景" },
  { name: "image13.gif", group: "抽象" },
  { name: "image14.webp", group: "人物" },
  { name: "image15.svg", group: "動物" },
  { name: "image16.jpg", group: "風景" },
  { name: "image17.png", group: "抽象" },
  { name: "image18.gif", group: "人物" },
  { name: "image19.webp", group: "動物" },
  { name: "image20.svg", group: "風景" },
  { name: "image21.jpg", group: "抽象" },
  { name: "image22.png", group: "人物" },
  { name: "image23.gif", group: "動物" },
  { name: "image24.webp", group: "風景" },
  { name: "image25.svg", group: "抽象" },
];
